#!/bin/bash

cur="$(readlink --canonicalize-existing .)"

# parse arguments, forward unkwon ones
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --podman) 
            USE_PODMAN=1;
            ;;
        --interactive) # run hol-light interactivly
            INTERACTIVE=1
            ;;
        --file) # file to load
            FILENAME=$2;
            shift; # past value
            ;;
        --help) 
            HELP=1
            ;;
        *) ARGS+=("$1");;
    esac
    shift
done

if [ $HELP ]
then
    echo "Examples: "
    echo "hol-light"
    echo "    to start an interactive HOL Light shell."
    echo "    type 'exit 0;;' to quit"
    echo "hol-light --file FILENAME"
    echo "    to open the given ml file in hol-light and execute it."
    echo "hol-light --file FILENAME --interactive"
    echo "    to open the given ml file in hol-light and execute it and keep HOL Light running."
    echo ""
    echo "Parameters: "
    echo "    --interactive, run hol-light interactivly. Enabled by default if no file is given. Disabled by default when a file is given."
    echo "    --podman, use podman instead of docker"
    echo "    --file FILENAME, include (#use) the file FILENAME inside HOL Light. By default the script is non interactive and terminates when it is processed, to make it interactive use --interactive."
    exit 0;
fi


if [ $USE_PODMAN ] 
then
    run_container() {
        podman container run --rm --interactive --tty --security-opt label=disable --hostname holbox --volume "$cur:/src" hol-light-core
    }
    clean_container() {
        # TODO: remove the kill all and handle this in a gracefuly way, keeping non related containers running
        podman kill --all
    }
else
    run_container() {
        docker container run --rm --interactive --tty --security-opt label=disable --hostname holbox --volume "$cur:/src" hol-light-core
    }
    clean_container() {
        # TODO: remove the kill all and handle this in a gracefuly way, keeping non related containers running
        docker kill --all
    }
fi

if [ $FILENAME ] 
then
    if [ $INTERACTIVE ] 
    then
        echo "Welcome to HOL Light"
        echo "type 'exit 0;;' to quit"
        (echo "#use \"/src/$FILENAME\";;") | run_container
    else
        (echo "#use \"/src/$FILENAME\";;"; echo 'exit 0;;') | run_container
    fi
else
    echo "Welcome to HOL Light"
    echo "type 'exit 0;;' to quit"
    run_container
fi

clean_container
